service_name: computer-records
service_port: "9119"
database_host: "localhost"
database_port: "5432"
database_name: "greenbone"
database_password: "pappi"
pulsar_url: "pulsar://127.0.0.1:6650"
pulsar_cert: ""
messaging_service_url: "http://localhost:8080/api/notify"